Repository nanato12/line-works-sdk, pull requests merged in 2025-02, with the labels that each got.

#47 update: README.md
  README.md
Labels: documentation

#48 fix: login logic
  VERSION
  line_works/client.py
  line_works/config.py
Labels: bug fix

#51 Add NOTIFICATION_FILE to mapping
  line_works/mqtt/models/payload/__init__.py
Labels: enhancement

#58 Fix: pypi GHA
  .github/workflows/publish_pypi.yml
Labels: GHA

#59 Revert "Refactor mqtt packets"
  line_works/mqtt/client.py
  line_works/mqtt/config.py
  line_works/mqtt/packets.py
Labels: bug fix
